name: "Import GPG Key"
description: "Imports a GPG key given in the input"
inputs:
  gpg-private-key:
    required: true
    description: "The GPG Private Key in plain text. Can be a sub-key."
runs:
  using: "composite"
  steps:
    # this is necessary because it creates gpg.conf, etc.
    - name: List Keys
      shell: bash
      run: |
        gpg -K --keyid-format=long

    - name: Import GPG Private Key
      shell: bash
      run: |
        echo "use-agent" >> ~/.gnupg/gpg.conf
        echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
        echo -e "${{ inputs.gpg-private-key }}" | gpg --import --batch
        for fpr in $(gpg --list-keys --with-colons | awk -F: '/fpr:/ {print $10}' | sort -u);
        do
          echo -e "5\\ny\\n" |  gpg --batch --command-fd 0 --expert --edit-key $fpr trust;
        done